### ISSUE TITLE
김태현의 코드 리뷰(느낀점)

### ISSUE THREAD

**Issue by ted0729** [ddoddiworld/My_React#2]
🗿 1) 전체적으로 컴포넌트가 분리되어있어서, 한 부분 한 부분 살펴보기 수월했습니다.

🗿 2) styled를 이용해서 각각의 컴포넌트에 맞는 css값을 넣어줘서 관리가 훨씬 용이해보입니다.

🗿 3) 구현해야 하는 화면은 시험조건내의 크기에서 깨지지않고 온전하게 보여지고, 기능 또한 전부 정상작동합니다.

🗿 4) 평소 주석이 없이는 코드를 이해하기가 힘든편인데, 각 변수값이 나타내는 의미도 명확하고,
정답을 보듯 가독성이 뛰어납니다. 또한 유효성 검사의 이용으로 굉장한 센스가 돋보입니다.

🗿 5) 개인적으로 컴포넌트 분리가 이번 주차의 강의에서 이해하기에 가장 복잡한 부분이었는데,
깔끔한 분리로 공부가 됬습니다.

항상 큰 도움 주시는 소영님 이번 코드 또한 저에게 큰 도움이되네요
🌟🌟!!! 항해 마지막까지 같이 파이팅입니다 !!! 🌟🌟

**Comment by ddoddiworld** [comment]
꼼꼼한 리뷰 감사합니다 😁!!

좋다고 생각된 부분은 앞으로도 발전시켜 나가겠습니다~!
오늘도 즐거운 코딩 하세요!!💻
